module.exports = {
  apps: [
    {
      name: 'feralde-auth-backend',
      script: 'artisan',
      interpreter: 'php',
      args: 'serve --host=0.0.0.0 --port=55001',
      cwd: '/home/feralde/feralde_auth',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        APP_ENV: 'staging',
      },
      error_file: './storage/logs/pm2-error.log',
      out_file: './storage/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: 'rz-auth-queue',
      script: 'artisan',
      interpreter: 'php',
      args: 'queue:work --tries=3 --sleep=3',
      cwd: '/home/feralde/feralde_auth',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      error_file: './storage/logs/pm2-queue-error.log',
      out_file: './storage/logs/pm2-queue-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};
